# Base Image
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1  
ENV PYTHONUNBUFFERED=1         

# Set the working directory in the container
WORKDIR /app


# Install Python dependencies
COPY requirements.txt /app/

RUN pip install -r requirements.txt

# Copy the application files
COPY . /app/

# Expose the port your app runs on
EXPOSE 5000

# Command to run the application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
